# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
          swift-version: 6.0
      - uses: actions/checkout@v4
      - name: Build
        run: make build
      - name: Run tests
        run: make test